### ISSUE TITLE
坐标系转换问题

### ISSUE THREAD

**Issue by cyqluowang** [TalkingData/Myna#10]
```
E/1-------->: -0.08379706,0.0023942017,9.830592------------1.8400628E-9,-5.106897E-10,9.83095
E/1-------->: -0.08379706,0.0023942017,9.830592------------1.8400628E-9,-5.106897E-10,9.83095
E/1-------->: -0.08379706,0.0023942017,9.830592------------1.1620958E-9,1.8825643E-9,9.83095
E/1-------->: -0.08379706,0.0023942017,9.830592------------2.7248013E-9,-2.220307E-9,9.83095
E/1-------->: -0.095768064,-0.007182605,9.840169------------3.9776635E-9,4.5439243E-9,9.840637
E/1-------->: -0.095768064,-0.007182605,9.840169------------3.9776635E-9,4.5439243E-9,9.840637
E/1-------->: -0.08379706,-0.02873042,9.78989-------------2.6502067E-9,3.6728203E-9,9.790292
E/1-------->: -0.08379706,-0.02873042,9.78989-------------2.6502067E-9,3.6728203E-9,9.790292
E/1-------->: -0.08379706,-0.02873042,9.78989-------------1.3617778E-9,1.0656152E-9,9.79029
```

为什么相同的坐标系转换后会不一样出现？

**Comment by cyqluowang** [comment]
而且x,y 轴的读数转换都是有问题的，只有z轴是对的

**Comment by xhrwang** [comment]
能否共享一下测试代码？
旋转矩阵的计算会使用到磁场传感器数据和重力传感器数据，二者任何一个有变化，都会导致旋转矩阵的改变，进而造成旋转后新坐标系下加速度传感器的值。

坐标系转换主要参考了：
Orientation 的计算：https://developer.android.com/guide/topics/sensors/sensors_position.html#sensors-pos-orient
RotationMatrix 的计算：https://developer.android.com/reference/android/hardware/SensorManager.html
执行转换的方法来自 Android OpenGL ES。

**Comment by cyqluowang** [comment]
代码里面
```
 if((int)(sd.game_rotation_vector[0]) == 0
                && (int)(sd.game_rotation_vector[1]) == 0
                && (int)(sd.game_rotation_vector[2]) == 0){
            SensorManager.getRotationMatrix(Rotate, I, sd.accelerate, sd.magnetic);
        }else{
            SensorManager.getRotationMatrixFromVector(Rotate, sd.game_rotation_vector);
        }
```
readme
```
SensorManager.getRotationMatrix(Rotate, I, sd.gravity, sd.magnetic);
```

**Comment by cyqluowang** [comment]
代码里面用了加速度， 解释里面用了重力，用的值不一样
还用了这个
 SensorManager.getRotationMatrixFromVector(Rotate, sd.game_rotation_vector);

**Comment by cyqluowang** [comment]
QQ: 1309944211方便联系么？帮助我下？

**Comment by xhrwang** [comment]
https://developer.android.com/reference/android/hardware/SensorManager.html#getRotationMatrix(float[], float[], float[], float[])

可以参考这里的说明：

gravity | float: is an array of 3 floats containing the gravity vector expressed in the device's coordinate. You can simply use the valuesreturned by a SensorEvent of a Sensor of type TYPE_ACCELEROMETER.

**Comment by cyqluowang** [comment]
研究过了，那你的意思是如果严谨的使用的话，需要传入gravity的数据？而不是accelerate？

**Comment by xhrwang** [comment]
是的，包含重力分量的加速度传感器数值也可以。

这个 Issue 先关闭了，如果还有问题，请随时提出。
