### ISSUE TITLE
这个东西到底能用来干嘛？

### ISSUE THREAD

**Issue by Gmle7** [TalkingData/Myna#11]
描述的不是很清楚，我反正是没有看懂

**Comment by xhrwang** [comment]
集成文档请参考 https://github.com/TalkingData/Myna/blob/master/QuickStart.md
Dataset 准备和模型训练请参考 https://github.com/TalkingData/Myna/tree/master/Dataset

目前这个框架可以基于传感器数据进行实时用户行为识别，也就是可以获取用户处于什么行为状态的信息，结合时间和基于位置的 POI，我们可以进一步理解用户在什么时候，什么地方，处于什么行为状态，从而提供更智能的推送或者服务。

这是一个在移动端进行机器学习以及深度学习方案部署的实践，我们也可以将 Image Classification，Object Detection 等针对移动端进行优化的模型通过类似的方式部署到移动端，开发对环境理解能力更智能的 AR 类应用等。

On Device AI 在 2017 年得到了硬件提供商，操作系统提供商的大力支持，如果对此感兴趣，可以参考我们整理的文章：[从服务器端到移动端的转折，On Device AI革命进行时](https://zhuanlan.zhihu.com/p/32565263)

**Comment by Gmle7** [comment]
谢谢解答疑惑
