### ISSUE TITLE
缺少数据

### ISSUE THREAD

**Issue by scucheri** [TalkingData/Myna#9]
找不到训练数据和测试数据，  train_feature_file = "0629_train.csv"    test_feature_file = "0629_test.csv" 这两个文件可否提供一下呀？

### logs:
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/scucheri/AllMyProjects/AI_android/Myna/Dataset/XGBoostrHAR.py
No record found in path: data/train
No record found in path: data/test
Traceback (most recent call last):
  File "/Users/scucheri/AllMyProjects/AI_android/Myna/Dataset/XGBoostrHAR.py", line 523, in <module>
    test_self_dataset()
  File "/Users/scucheri/AllMyProjects/AI_android/Myna/Dataset/XGBoostrHAR.py", line 468, in test_self_dataset
    train = np.loadtxt(train_feature_file, delimiter=',')
  File "/Library/Python/2.7/site-packages/numpy/lib/npyio.py", line 896, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: '0629_train.csv'

Process finished with exit code 1

**Comment by scucheri** [comment]
![image](https://user-images.githubusercontent.com/10495849/28705826-1d23e3c6-73a4-11e7-9768-d5d26ccfb9f9.png)

app 端的这个数据在哪里可以找到呢？

**Comment by scucheri** [comment]
知道了哈，运行python 训练数据需要在同目录下加入数据，如下：
![image](https://user-images.githubusercontent.com/10495849/28862927-7508f77c-7799-11e7-9eaf-4726305757e1.png)

在手机上运行需要将上面的数据放到手机的sdcard根目录下

**Comment by xhrwang** [comment]
OK, Thanks. close this thread now.
